server:
  port: 8090
spring:
  profiles:
    active: prod
  cloud:
    gateway:
      routes:
        - id: api-interface
          predicates:
            - Path=/api/**
  redis:
    port: 6379
    database: 3
dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    parameters[namespace]: lyc