spring:
  profiles:
    active: dev
  application:
    name: qi-api-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qi_api
    username: root
    password: root
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1

#  邮箱配置
  mail:
    host: smtp.qq.com
    username: 1360572433@qq.com
    # qq邮箱授权码
    password: xwjnjhmeykokicje
    emailFrom: 1360572433@qq.com
    # 开启加密授权验证
    properties:
      mail:
        smtp:
          ssl:
            enable: true
server:
  port: 7529
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        # 一周
        max-age: 604800
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

## 腾讯云cos配置
cos:
  client:
    accessKey: xxxxxxx
    secretKey: xxxxxxx
    region: xxxxxxx
    bucket: xxxxxxx
# 微信支付配置
wx:
  pay:
    appId: wxxxxxxxxx67e8dc
    mchId: 1x0xxxx68
    apiV3Key: xxxxxbxxx3xxxx3xxx4
    privateKeyPath: classpath:/pem/apiclient_key.pem
    privateCertPath: classpath:/pem/apiclient_cert.pem
    notifyUrl: https://beloved-massive-sheepdog.ngrok-free.app/api/order/notify/order
# 支付宝支付配置
alipay:
  appId: 9021000122688504
  sellerId: 2088721004142050
#  notifyUrl: https://beloved-massive-sheepdog.ngrok-free.app/api/order/notify/order
  notifyUrl: http://localhost:8000/api/order/notify/order
  returnUrl: http://localhost:8000/account/center
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCeZWuGDpibW3yG1/uydy/nXMyz8FF840l4HYgyDMNouc/DFrq9gGrgaDb3nF/Jka29Lb2mhi0uliqEjBi1XX4WNrJH2fwfuDBwWMV7WEXXE/ck+FUapafgablwUUPokJIVyFcAJU050I20JtvKoxiYfORCaNLz6OKOJAe0aiSPT/vkxyCmdHP7Kwonc6Hmq5r8yNJMYS1WvSv9IltlwhF0h+NJE4os8CfOtzNmjbRqc/k35Hhkvux6mxzFQl1Y7ttf5WPLf7VfFd4rmC+W8O6schIkBF2s+3Ph0CnDSGOwapvHlYTqm6OoR5snktf6zhu5H3eG8ZtgFbbf12c8tRbVAgMBAAECggEACQKb6zRJWg0KOGFw3+YHw5Fz04iIGiKTu1FyveYb94kaWG6ikMUNT1aeSdeLW1v+FhTUBPT8/Plt0bxma2q2EW1rFss/nE5N8xYZpbqPvnxUQrYdoTZrJkjdU5ZL1p7isHqE+G0mx3MlnGnZdt1wOLxh/6UW2ukUeiFyjsC686vyDUks0kFgK18cw/544Usmh1hnQ0Hh1Hd2QxUpi01PUdkuQetNdEnkZxZQQ5T7nPM8MpD7ep78zUeWYKtek0w5Ut9/kwksxdPwboAuPAje1J1SDIljQXaC8IyDC1i3Dc6p4zjo7d5gclLhldckCJGhb8Vp6CVrQtfCnz5JYctKwQKBgQDgSWOSG75BCu7edn/aS5Gge9tfHLMYfOMcPV/TRcKn58Vz1ngina/429f44wonob0YyExkI8Qir22Rx+w3EWJRw6ozr90dK7ALKv5YQWFSEe5Y1z6SYbwuGLcew4jLmxbN7hu3XrIotsMB0+TC84Nk2zj7aHpt5oxDP2ikEkHlswKBgQC0yvYXGJHGY6Yv32zaTNDtJc7IFcgZ6JiAMT3RtPOyH2c8JQpq4j+WKRJc/jWYvLUmWumEn9lRMQ6HIGAW/TGTj4ogjUzoeaqc/3XOze50H7kaaI3GJ2rrNM8ut4ZL0wMR1xYVmJhKjU5+W97YnoZ02Qj6o3S/CULCQMhDtapdVwKBgG9iowt1sbeVmWlryjT8IJdly11h4GPB6fwlUsiWtYQza3EKyuDOFQ1vCMP25R0nisSa/K0iwg5DtxOWCO6UOJLIrGc86H/LKYNyV5w25AEhHJCMXOvPk+gEqDSkAPS00c91d9hKNApaMWBf/hT/YHqfEJ5ylZKs0222ON56nrVXAoGBAJ+eFZkciw9xyTa49rzhVxAY8jC68ljVf1amouKz9PgNO7LhLQpiyCsGBf1uPtmjufesCkGac154hlAM6GlDj3KtJxFIT19sk5JbBKLaM634mA9Vwd3xzTbuAAFJ7Nqi6THmCMx2VfZ0PZnX+K6dfy5Is+G9UISdY4Bne6g0Cr6vAoGAL1/YgKXcKMiK4oB4xiKrc/T11sRToq6irsqz9Lpl7hLZa1/wM1LgDG0oeBY4XAyqxC337MgPe1q91UYfiWpQeDa85/KfPmrgAEAYpBp3WlDmqaXS2FHgR5VNTw4Z9LHwvw5tKjMspeOlGhtiI46qiI4caEqfhVYHD6qu3AcVSEk=
  ali-pay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA31mbEUg8s4GdUJm7zBVJwRjA1pdu27H5A1GroEtp2gDN6/mECLYZWzr3v0M+sYendStIo7FebAHYkj3F8WOi/Z7rDdYkI//JsuegESuvcaQSPrikCpwTWEe2FUlIBPyemWRmm7JEsw1wETlBznHZ1SOdAHN6oAm4dZzNFzH+9YSLo9ehYpeW5RtD15kf5ePR2G33xBJgeY0TaFhD1rEc8jNbUen1DdFkF/ReGgcWS/I9ryfm+z7Mevny2JmAHicC+syx9LfnXhHf8Ezdhr66Y69az5BmbMrQopQO4RXcChdKCF5Ner2BzwpJ9/KezFYdoMTfMCuIBStq4fL5Y4ldNwIDAQAB
dubbo:
  application:
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
    parameters[namespace]: qi

qi:
  api:
    client:
      access-key: 9235bf9ad7215cd96a69301f0e577629
      secret-key: a24d28e2418520503dbf59820f61f9f0
#       本地网关地址，可修改为自己的网关，用于本地测试，或者线上网关地址等
      host: http://localhost:8090/api